CREATE TABLE art_work (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    inventory_number TEXT DEFAULT '',
    artist TEXT DEFAULT '',
    title TEXT DEFAULT '',
    description TEXT DEFAULT '',
    short_desc TEXT DEFAULT '',
    is_highlight INTEGER DEFAULT 0, -- 0 for false, 1 for true
    art_movement TEXT DEFAULT '',
    artwork_type TEXT DEFAULT '',
    genre TEXT DEFAULT '',
    subject TEXT DEFAULT '',
    depicts TEXT DEFAULT '',
    place_of_origin TEXT DEFAULT '',
    artwork_wikipedia_url TEXT DEFAULT '',
    artwork_museum_url TEXT DEFAULT '',
    data_source TEXT DEFAULT '',
    image_wikimedia_url TEXT DEFAULT '',
    primary_image_small TEXT DEFAULT '',
    primary_image_medium TEXT DEFAULT '',
    primary_image_large TEXT DEFAULT '',
    primary_image_original TEXT DEFAULT '',
    artwork_date TEXT DEFAULT '',
    museum_location TEXT DEFAULT '',
    museum TEXT DEFAULT '',
    dimension TEXT DEFAULT '',
    cat_no TEXT DEFAULT '',
    color TEXT DEFAULT ''
);
