
// src/errors/errorCodes.ts
export const ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_INPUT:'INVALID_INPUT',
  INVALID_PARAMS:'INVALID_PARAMS',

  //user
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  

 
  FAVORITE_EXISTS: 'FAVORITE_EXISTS',
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',

  DATABASE_ERROR: 'DATABASE_ERROR'
} as const;
